[package]
name = "hello_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.34.0", features = ["full"] }
