apiVersion: 2019-12-01
location: eastus
name: myvirtualbot
properties:
  imageRegistryCredentials: # Credentials to pull a private image
    - server: index.docker.io
      username: sagarmhatre@yahoo.com
      password: Passw0rd
  containers:
  - name: myvirtualbot
    properties:
      environmentVariables:
        - name: 'ClientId'
          secureValue: 'eudemo03-apac'
        - name: 'ClientSecret'
          secureValue: 'Zx0PGdF***********iKvDffXH'
        - name: 'AXP_VIRTUAL_BOT_DOMAIN_LABEL'
          value: 'https://axpvirtualbot.eastus.azurecontainer.io'
        - name: 'IPAAS_URL'
          value: 'https://prod-59.eastus.logic.azure.com:443/workflows/31e4035410344ef59c9810be6d47ea79/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=DGytUW39-o0i1dDKowzxPVMGaavUrlFSlKcvtRahS4Q'
        - name: 'domainName'
          value: 'eudemo03.avaya.com'
        - name: 'tenantId'
          secureValue: 'HHCKCY'         
        - name: 'port'
          secureValue: '443'                 
      image: sagarmhatre/sagar-pvt:1.1-amd64
      ports: 
        - protocol : 'tcp'
          port : '443'
      resources: # Resource requirements of the instance
        requests:
          memoryInGB: 1.5
          cpu: 4.0
        limits:
          memoryInGB: 1.5
          cpu: 4.0
      livenessProbe:
        httpGet:
          httpHeaders:
          path: /health
          port: 443
        initialDelaySeconds: 30
        periodSeconds: 30
        failureThreshold: 3
        successThreshold: 1
        timeoutSeconds: 5
  osType: Linux
  ipAddress: # IP address configuration of container group
    ports:
      - protocol : 'TCP'
        port : '443'
    type: Public
    dnsNameLabel: myvirtualbot
    # dnsNameLabelReusePolicy: TenantReuse  
  restartPolicy: OnFailure
tags: null
type: Microsoft.ContainerInstance/containerGroups

# Full Specs : https://learn.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml

# To deploy
# az container create --resource-group my-resourcegrp --file my-filename.yaml 